services:
  app:
    build:
      target: deps
    command: sh -c "npm run dev"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app:Z
      - /app/node_modules
    ports:
      - "9229:9229"

  db:
    ports:
      - "${DB_PORT:-5432}:5432"
